name: Rails CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Install dependencies
        run: bundle install

      - name: Setup DB
        run: bundle exec rails db:setup

      - name: Migrate DB
        run: bundle exec rails db:migrate

      - name: Run tests
        run: bundle exec rake